### ISSUE TITLE
Eagle Files of Universal Flush Interface not complete

### ISSUE THREAD

**Issue by philoepp** [KONNEKTING/KonnektingHardware#3]
Hi,
is there a reason that the latest update of the eagle files of the universal flush interface is not publicated yet, only a pdf from the schematic?

Best regards
Philipp

**Comment by Adminius** [comment]
Hi,

the reason is: i will sell it :)
So, if you want PCBs pls contact me. 
The Eagle Files on github are only for refernce, e.g. if you will make an additional PCB for UFI e.g. with sensors.

Best regards
Eugen
