### ISSUE TITLE
Eagle files for the MicroBCU

### ISSUE THREAD

**Issue by rml4o** [KONNEKTING/KonnektingHardware#4]
Hello,

Great work with this repo ! Would you have the Eagle files for the MicroBCU ?
I would like to build one myself.
Thanks,

Armel

**Comment by Adminius** [comment]
Hi, sorry, no. 
But you can buy it

**Comment by rml4o** [comment]
Great! Where can it be bought from?

**Comment by Adminius** [comment]
@rml4o pls contact me: eugenius707 (at) gmail com

**Comment by rml4o** [comment]
That sounds interesting - will it work with Franck Marini's "KNX Bus Device library for Arduino", which was designed for the TPUART? Or is the format of the UART data for the NCN5120 different from the format used by the TPUART?
Thanks!

**Comment by Adminius** [comment]
@rml4o NCN5120 has mostly the same UART data format.
our library works perfect with it. 
Standalone Frank's library may have some issues with it: https://github.com/KONNEKTING/KonnektingDeviceLibrary/issues/41

But it is antother topic. 
Eagle-files question is clear now. i close this issue.
